Add error message if local file doesn't exist. (#3900)
* Add error message if local file doesn't exist.

This commit addresses issue #3382.

Previously, if you tried to open a non-existent local file, you'd get an
error message like this:

ValueError: No plugin found capable of reading
'/path/to/nonexistent/file'

This commit provides a hopefully more helpful error message:

ValueError: Requested path '/path/to/nonexistent/file' does not exist.

* Move existence check into abspath_or_url

* add must_exists

* Fix typo: must_exists -> must_exist

Co-authored-by: Matthias Bussonnier <bussonniermatthias@gmail.com>
Co-authored-by: Nicholas Sofroniew <sofroniewn@gmail.com>
Co-authored-by: Juan Nunez-Iglesias <juan.nunez-iglesias@monash.edu>