Fix AttributeError: 'LayerList' object has no attribute 'name' (#4276)
* fix #4217

* fix base too

* layer can be none

* undo change

Co-authored-by: Matthias Bussonnier <bussonniermatthias@gmail.com>