Guard against stale index for layer paint methods (#9149)
# References and relevant issues

Found while working on #8391

# Description

This guards against stale indexes being passed to the LayerDelegate
paint methods.
This can happen when a layer is removed while an async paint event is
queued, and thus
the index is no longer valid. This is guard against already in
`get_layer_icon()`, but now this
also protects other methods like the `_paint_loading` bug that happened
here.

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\Documents\GitHub\napari\src\napari\_qt\containers\_layer_delegate.py:106, in LayerDelegate.paint(self=<napari._qt.containers._layer_delegate.LayerDelegate object>, painter=<PyQt6.QtGui.QPainter object>, option=<PyQt6.QtWidgets.QStyleOptionViewItem object>, index=<PyQt6.QtCore.QModelIndex object>)
    104 super().paint(painter, option, index)
    105 # paint loading indicator if needed
--> 106 self._paint_loading(painter, option, index)
        option = <PyQt6.QtWidgets.QStyleOptionViewItem object at 0x000001EF37DC9950>
        index = <PyQt6.QtCore.QModelIndex object at 0x000001EF37DCADD0>
        painter = <PyQt6.QtGui.QPainter object at 0x000001EF37DCB050>
        self = <napari._qt.containers._layer_delegate.LayerDelegate object at 0x000001EEBFC16990>    107 # paint the thumbnail
    108 self._paint_thumbnail(painter, option, index)

File ~\Documents\GitHub\napari\src\napari\_qt\containers\_layer_delegate.py:149, in LayerDelegate._paint_loading(self=<napari._qt.containers._layer_delegate.LayerDelegate object>, painter=<PyQt6.QtGui.QPainter object>, option=<PyQt6.QtWidgets.QStyleOptionViewItem object>, index=<PyQt6.QtCore.QModelIndex object>)
    147 self._load_movie.start()
    148 load_rect = option.rect.translated(4, 8)
--> 149 h = index.data(Qt.ItemDataRole.SizeHintRole).height() - 16
        index = <PyQt6.QtCore.QModelIndex object at 0x000001EF37DCADD0>
        Qt.ItemDataRole.SizeHintRole = <ItemDataRole.SizeHintRole: 13>
        Qt = <class 'PyQt6.QtCore.Qt'>    150 load_rect.setWidth(h)
    151 load_rect.setHeight(h)

AttributeError: 'NoneType' object has no attribute 'height'
```

---------

Co-authored-by: Juan Nunez-Iglesias <jni@fastmail.com>
Co-authored-by: Peter Sobolewski <76622105+psobolewskiPhD@users.noreply.github.com>