Fix handling of units and axis_labels in add_image (#7089)
# Description

The new `axis_labels` and `units` arguments for layers are iterables;
they need to be added to the iterable arguments to avoid problems with
the channel splitting in the case of an image stack.

Currently, this fails:

```py
import napari
import numpy as np
v = napari.Viewer()
a = np.random.rand(2, 2)
v.add_image(a, axis_labels=('x', 'y'))
```

with:

```
TypeError: Received sequence for argument 'axis_labels', did you mean to specify a 'channel_axis'?
```