Update branch name, for update dependencies workflow, to avoid branch name collisions, that prevents push (#7822)
# References and relevant issues

Follow up to #7821

# Description

Today I learned that if you have branch `branch/something` you cannot
have branch `branch`

```
stderr: To https://github.com/napari-bot/napari.git
 ! [remote rejected] auto-update-dependencies -> auto-update-dependencies (cannot lock ref 'refs/heads/auto-update-dependencies': 'refs/heads/auto-update-dependencies/Carreau/napari/qtpy6-mypy' exists; cannot create 'refs/heads/auto-update-dependencies')
error: failed to push some refs to 'https://github.com/napari-bot/napari.git'
```

So this PR add suffix `-main` to distinguish it.