Add tests for popup widgets and fix perspective popup slider initialization (#5848)
# Fixes/Closes

Closes #3794

# Description

This adds some tests to check for popup widgets functionality (popups
that are launched from the buttons that handle some viewer functionality
and from the dims slider play button):

* dims slider play button -> play settings (fps, play mode, loop mode)
popup
* roll dims button -> dims order/sorter popup
* grid button -> grid settings (grid stride, width and height) popup
* ndisplay button -> perspective slider popup

While checking this, I noticed an issue with the perspective popup that
can be launched from the ndisplay button:

<details>

```python-traceback
Traceback (most recent call last):
  File "E:\Acer\Documentos\Quansight\Napari\napari\napari\_qt\widgets\qt_viewer_buttons.py", line 186, in open_perspective_popup
    sld.setValue(self.viewer.camera.perspective)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'
```

</details>

So I added in this PR the missing cast to `int` so the related new test
can pass.

## Notes: 

Checking the logic the popups creation follows in the `QtViewerButtons`
class, maybe could be worthy to move the detailed widget creation for
popups (like the perspective and grid settings popups) to be in its own
class definition? So, change all the popups that are created from the
viewer buttons to follow a similar approach like the one the dims sorter
popup uses where a `QtDimsSorter` class is defined?

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue) - add tests

# How has this been tested?
- [x] all tests pass with my change
- [x] I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

---------

Co-authored-by: Peter Sobolewski <76622105+psobolewskiPhD@users.noreply.github.com>