Fix harvesting plugins from CLI (#8728)
# References and relevant issues

[#general > force a reader, regardless of extension @
💬](https://napari.zulipchat.com/#narrow/channel/212875-general/topic/force.20a.20reader.2C.20regardless.20of.20extension/near/577089110)

# Description

`napari --plugin-info` results in a traceback (see bottom)
The fix is simply due to a change in the API in npe2. We don't need to
worry about backwards compat bc we pin npe2 to the current version.

```python
napari --plugin-info
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name            ┃ Version                            ┃ Npe2 ┃ Contributions                                                                     ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ napari          │ 0.7.0a4.dev50+g742bf41fd.d20260306 │ ✅   │ commands (43), readers (2), writers (6), widgets (1), sample_data (34), menus (2) │
│ napari-console  │ 0.1.4                              │ ✅   │                                                                                   │
│ napari-metadata │ 0.2.0a1.dev8+g8b2bfd3d6            │ ✅   │ commands (1), widgets (1)                                                         │
│ napari-svg      │ 0.2.1                              │ ✅   │ commands (1), writers (1)                                                         │
│ nbatch          │ 0.0.4                              │ ✅   │                                                                                   │
│ ndev-settings   │ 0.4.1                              │ ✅   │ commands (1), widgets (1)                                                         │
│ ndev-themes     │ 0.1.1                              │ ✅   │ themes (1)                                                                        │
│ ndevio          │ 0.9.0                              │ ✅   │ commands (9), readers (1), widgets (2), sample_data (6)                           │
│ ome-types       │ 0.6.3                              │ ✅   │ commands (1), widgets (1)                                                         │
└─────────────────┴────────────────────────────────────┴──────┴───────────────────────────────────────────────────────────────────────────────────┘
```

## Bug

```pytb
napari --plugin-info
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\timmo\Documents\GitHub\napari\.venv\Scripts\napari.exe\__main__.py", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\timmo\Documents\GitHub\napari\src\napari\__main__.py", line 374, in main
    _run()
    ~~~~^^
  File "C:\Users\timmo\Documents\GitHub\napari\src\napari\__main__.py", line 216, in _run
    args, kwargs = parse_sys_argv()
                   ~~~~~~~~~~~~~~^^
  File "C:\Users\timmo\Documents\GitHub\napari\src\napari\__main__.py", line 200, in parse_sys_argv
    args, unknown = parser.parse_known_args()
                    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\timmo\AppData\Roaming\uv\python\cpython-3.13.11-windows-x86_64-none\Lib\argparse.py", line 1908, in parse_known_args
    return self._parse_known_args2(args, namespace, intermixed=False)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\timmo\AppData\Roaming\uv\python\cpython-3.13.11-windows-x86_64-none\Lib\argparse.py", line 1937, in _parse_known_args2
    namespace, args = self._parse_known_args(args, namespace, intermixed)
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\timmo\AppData\Roaming\uv\python\cpython-3.13.11-windows-x86_64-none\Lib\argparse.py", line 2188, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\timmo\AppData\Roaming\uv\python\cpython-3.13.11-windows-x86_64-none\Lib\argparse.py", line 2112, in consume_optional
    take_action(action, args, option_string)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\timmo\AppData\Roaming\uv\python\cpython-3.13.11-windows-x86_64-none\Lib\argparse.py", line 2013, in take_action
    action(self, namespace, argument_values, option_string)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\timmo\Documents\GitHub\napari\src\napari\__main__.py", line 39, in __call__
    cli.list(
    ^^^^^^^^
AttributeError: module 'npe2.cli' has no attribute 'list'. Did you mean: 'list_'?
```

## Follow-up

We should test __main__ so we don't reintroduce these past two pretty
crappy bugs

---------

Co-authored-by: Lorenzo Gaifas <brisvag@gmail.com>