Minor refactor of get_active_layer_dtype
I realised after reviewing #3402 that the getattr() fallback doesn't buy
us anything in that function, because str objects don't have a __name__
attribute:

```
 $ python -c "print(''.__name__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'str' object has no attribute '__name__'
```

This refactors that function's flow to be more robust to unexpected
values.