Print contend of stderr and stdout in update dependecies workflow (#7817)
# References and relevant issues


# Description

When `Upgrade test constraints` fails, then Traceback does not contain
stderr and stdout so we do not know why it fails.

Here example part of traceback

```
INFO:root:Force pushing to auto-update-dependencies
Traceback (most recent call last):
  File "/home/runner/work/napari/napari/tools/create_pr_or_update_existing_one.py", line 348, in <module>
    main()
  File "/home/runner/work/napari/napari/tools/create_pr_or_update_existing_one.py", line 335, in main
    create_pr_with_push(branch_name, access_token)
  File "/home/runner/work/napari/napari/tools/create_pr_or_update_existing_one.py", line 135, in create_pr_with_push
    push(new_branch_name)
  File "/home/runner/work/napari/napari/tools/create_pr_or_update_existing_one.py", line 83, in push
    subprocess.run(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'push', '--force', '--set-upstream', 'origin', 'auto-update-dependencies']' returned non-zero exit status 128.
```