improve stack trace of autogenerated `ViewerModel.add_xxxx` methods (#6791)
# References and relevant issues

The problem is visible in stacktrace from here
https://github.com/napari/napari/issues/6789#issue-2214508767


# Description

Instead of using a string template and passing source file name, create
template file and pass the path to it to compile function.

On main:

```python
Traceback (most recent call last):
  File "/home/czaki/Projekty/napari/examples/add_points.py", line 22, in <module>
    viewer.add_points(points, size=size)
  File "/home/czaki/Projekty/napari/napari/components/viewer_model.py", line 7, in add_points
    from collections.abc import Iterator, Sequence
                ^^^^^^^^^^^^^^^^
  File "/home/czaki/Projekty/napari/napari/layers/base/base.py", line 112, in __call__
    raise ValueError("sample exception")
ValueError: sample exception
``` 

with this PR:

```python
Traceback (most recent call last):
  File "/home/czaki/Projekty/napari/examples/add_points.py", line 22, in <module>
    viewer.add_points(points, size=size)
  File "/home/czaki/Projekty/napari/napari/utils/add_layer.py_tmpl", line 7, in add_points
    layer = {cls_name}(**kwargs)
            ^^^^^^^^^^^^^^^^
  File "/home/czaki/Projekty/napari/napari/layers/base/base.py", line 112, in __call__
    raise ValueError("sample exception")
ValueError: sample exception
```

You can see that before this change, `from collections.abc import
Iterator, Sequence` points to an incorrect line of code regarding the
source of the error.