Wrap Labels multiscale data in MultiScaleData object in setter (#8922)
# References and relevant issues
Bug discovered during https://github.com/napari/napari/pull/8917 testing

# Description
Currently, Labels layers do not wrap their multiscale data in a
MultiScaleData class during the data setter. This causes an
`AttributeError: 'list' object has no attribute 'shape'` on:
https://github.com/napari/napari/blob/c3e6c4ab549eaeb67c6f98502851dd99e4804522/src/napari/layers/labels/labels.py#L604

Solution: do the same thing as the Image layer, save the original in
`self._raw_data` (inherited from `ScalarBaseField`) and wrap self._data
in `MultiScaleData` if self.multiscale is True. MultiScaleData has an
ndim field, so this fixes the issue. There remains an issue with
resetting the data_level if you reassign with new MultiScaleData that
has fewer resolution levels, but this will be fixed in #8917 . Since the
`ScalarFieldBase` has no data setter, I couldn't put the fix there, so
duplicating the 2 lines of code seemed easiest.

---------

Co-authored-by: Peter Sobolewski <76622105+psobolewskiPhD@users.noreply.github.com>