Add napari-metadata to napari dependencies (#8576)
# Description

[napari/napari-metadata](https://github.com/napari/napari-metadata) is
being publicly released.
@carlosmariorr and I propose adding napari-metadata to core
dependencies.

The dependencies of napari-metadata are only `qtpy`, `numpy`, `pint`,
all core dependencies of napari. For this reason, we believe that the
value add of napari-metadata is as much for every user as something like
napari-console, since it directly, and only, exposes public napari API
in a GUI.

Alternatively, this could be added as an optional dependency.

Currently, all constraints are updated because passing a package that
does not yet exist in the constraints is not allowed with the new bash
script.
```
bash -l tools/compile_constraints.sh napari-metadata                  
Notice: package 'napari-metadata' not found in resources/constraints/*.txt
Error: the following packages were not found in resources/constraints/*.txt: napari-metadata
```

- [x] fix constraints
- [x] find and add @carlosmariorr orcid to citation

---------

Co-authored-by: Carlos Rodriguez <carlosmariorr90@hotmail.com>