Add configurable suffix for test artifacts (#8069)
# References and relevant issues

# Description

Allow to add optional suffix for artifacts to avoid false negative test
crash because of artifacts name.

When debugging test failing only on a specific CI configuration, it may
be a good idea to copy such a configuration into "Initial test" section
to reduce CI usage. But once the test passed, we got a false negative
test suite crash because of conflict of artifacts name.



https://github.com/napari/napari/actions/runs/16061339574/job/45328714764?pr=7950


![image](https://github.com/user-attachments/assets/23d69dcd-a914-4a61-83bb-6dcc55c81937)


```
Run actions/upload-artifact@v4
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

Also configure artifacts for the initial section to reduce changes in
future PRs.