protect against setting corner_pixels with extent 0 for multiscale images (#3866)
* protect against setting corner_pixels with extent 0

* add test cases

prior to the changes in gh-3866 this test raises with:
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE

* skip new multiscale test on windows CI