Update event connection order (#7150)
# References and relevant issues

In PartSeg I got multiple such reports:

```python
ValueError: Volume visual needs a 3D array.
  File "PartSeg\common_gui\napari_image_view.py", line 682, in _add_image
  File "PartSeg\common_gui\napari_image_view.py", line 645, in _add_layer_util
  File "napari\components\viewer_model.py", line 742, in add_layer
  File "_collections_abc.py", line 1128, in append
  File "napari\components\layerlist.py", line 188, in insert
  File "napari\utils\events\containers\_selectable_list.py", line 68, in insert
  File "napari\utils\events\containers\_evented_list.py", line 202, in insert
  File "napari\utils\events\event.py", line 764, in __call__
  File "napari\utils\events\event.py", line 802, in _invoke_callback
  File "napari\utils\events\event.py", line 789, in _invoke_callback
  File "napari\_qt\qt_viewer.py", line 658, in _on_add_layer_change
  File "napari\_qt\qt_viewer.py", line 668, in _add_layer
  File "napari\_vispy\utils\visual.py", line 88, in create_vispy_layer
  File "napari\_vispy\layers\image.py", line 89, in __init__
  File "napari\_vispy\layers\scalar_field.py", line 71, in __init__
  File "napari\_vispy\layers\scalar_field.py", line 123, in _on_data_change
  File "vispy\visuals\volume.py", line 852, in set_data
  ```

# Description

When try to debug the above error, I have found that the callback order looks incorrect 

![obraz](https://github.com/user-attachments/assets/20ff8bb1-e246-40a1-a379-f58f8b3845d6)

so `QtViewer._on_add_layer_change` is called before `Viewer._on_add_layer` when the `Viewer._on_add_layer` is triggering data slicer, so  data slice value may be incorrect. 

I think that after #4480 we should keep events in connection order. So Qt updates will be triggered after core models updates 

This PR also updates the code for fixing data shape  to work good with data of `ndim=1`


This PR is a workaround problem that is reported to me as it happens on Windows, on long living sessions.