Add error message if local file doesn't exist.
This commit addresses issue #3382.

Previously, if you tried to open a non-existent local file, you'd get an
error message like this:

ValueError: No plugin found capable of reading
'/path/to/nonexistent/file'

This commit provides a hopefully more helpful error message:

ValueError: Requested path '/path/to/nonexistent/file' does not exist.