Stop welcome screen time on hiding of QtWiewer (#8585)
# References and relevant issues

# Description

When opening a viewer in an IPython session and closing it without
layers, then after a few seconds, there is an error

```
vWARNING: Traceback (most recent call last):
  File "/home/czaki/.pyenv/versions/napari_3.12/bin/ipython", line 10, in <module>
    sys.exit(start_ipython())
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/IPython/__init__.py", line 139, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/IPython/terminal/ipapp.py", line 325, in start
    self.shell.mainloop()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/IPython/terminal/interactiveshell.py", line 1009, in mainloop
    self.interact()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/IPython/terminal/interactiveshell.py", line 994, in interact
    code = self.prompt_for_code()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/IPython/terminal/interactiveshell.py", line 944, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1035, in prompt
    return self.app.run(
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/prompt_toolkit/application/application.py", line 978, in run
    result = loop.run_until_complete(coro)
  File "/home/czaki/.pyenv/versions/3.12.9/lib/python3.12/asyncio/base_events.py", line 678, in run_until_complete
    self.run_forever()
  File "/home/czaki/.pyenv/versions/3.12.9/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/home/czaki/.pyenv/versions/3.12.9/lib/python3.12/asyncio/base_events.py", line 1961, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/prompt_toolkit/eventloop/inputhook.py", line 150, in select
    self.inputhook(InputHookContext(self._r, input_is_ready))
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/IPython/terminal/pt_inputhooks/qt.py", line 88, in inputhook
    _exec(_eventloop)
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/IPython/terminal/pt_inputhooks/qt.py", line 16, in _exec
    obj.exec() if hasattr(obj, "exec") else obj.exec_()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/app/backends/_qt.py", line 1040, in _vispy_timeout
    self._vispy_timer._timeout()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/app/timer.py", line 160, in _timeout
    self.events.timeout(
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/czaki/Projekty/napari/src/napari/_vispy/overlays/welcome.py", line 84, in next_tip
    self.node.set_tip(next(self.tips_iterator))
  File "/home/czaki/Projekty/napari/src/napari/_vispy/visuals/welcome.py", line 123, in set_tip
    self.tip.text = 'Did you know?\n' + '\n'.join(
    ^^^^^^^^^^^^^
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/util/frozen.py", line 17, in __setattr__
    object.__setattr__(self, key, value)
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/visuals/text/text.py", line 462, in text
    self.update()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/scene/node.py", line 334, in update
    c.update(node=self)
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/scene/canvas.py", line 209, in update
    super(SceneCanvas, self).update()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/app/canvas.py", line 455, in update
    self._backend._vispy_update()
  File "/home/czaki/.pyenv/versions/3.12.9/envs/napari_3.12/lib/python3.12/site-packages/vispy/app/backends/_qt.py", line 480, in _vispy_update
    self.update()
RuntimeError: wrapped C/C++ object of type CanvasBackendDesktop has been deleted
ERROR: Invoking <bound method VispyWelcomeOverlay.next_tip of <napari._vispy.overlays.welcome.VispyWelcomeOverlay object at 0x778168afd7f0>> for Event
```

This PR is fixing this problem by stopping the timer when `QtViewer` is
hidden. And the hide event is triggered on close of Viewer too.

Because `QtViewer` dostring is documenting `show_welcome_screen`
attribute this PR is also restoring this attribute.

https://github.com/napari/napari/blob/30941b34a2386423f07c7dfbe73efd639923f624/src/napari/_qt/qt_viewer.py#L152-L160

---------

Co-authored-by: Draga Doncila Pop <17995243+DragaDoncila@users.noreply.github.com>