Add pyqt5-qt5 pin for `uv add` compatability on Windows (#7744)
# References and relevant issues

`uv add napari[all]` (or some equivalent installing pyqt5) will result
in the following error:
```
error: Distribution `pyqt5-qt5==5.15.16 @ registry+https://pypi.org/simple` can't be installed because it doesn't have a source distribution or wheel for the current platform

hint: You're on Windows (`win_amd64`), but `pyqt5-qt5` (v5.15.16) only has wheels for the following platforms: `manylinux2014_x86_64`, `macosx_10_13_x86_64`, `macosx_11_0_arm64`
```
This also occurs when using `uv sync` on a project with napari as a
dependences. However, `uv pip install napari[all]` does solve correctly.
So, this fix is specifically for `uv add/sync`.

I've been having this problem for quite a while in various projects, and
this is the cleanest and most intuitive work around I have found so far.

# Description

Adds a pin for `pyqt5-qt5` for windows, so that `uv add` solves
correctly.